---
- name: Install pgbouncer
  apt: pkg=pgbouncer state=installed update-cache=yes

- name: Install pgbouncer config
  action: template src=pgbouncer.ini.j2 dest=/etc/pgbouncer/pgbouncer.ini
          mode=0600 owner={{ pgbouncer.user }} group={{ pgbouncer.group }}
  tags: credentials
  notify: pgbouncer restart

- name: Enable pgbouncer
  lineinfile: dest=/etc/default/pgbouncer regexp="^START=\d$" line="START=1"

- name: Start pgbouncer
  service: name=pgbouncer state=started
