---
- name: "Install aptitude if not already installed"
  apt: name=aptitude state=latest update_cache=yes
  sudo: yes

- name: "Update all packages"
  apt: upgrade=safe
  sudo: yes

- name: "Install common packages"
  apt: name={{item}} state=latest
  with_items:
    - git
    - python-pip
    - python-dev
    - iotop
    - htop
    - unzip
    - realpath
    - apache2-utils
    - ntp
  sudo: yes

- name: "Setup Locales (Ubuntu)"
  shell: echo 'LC_ALL=en_US.UTF-8\nLANG=en_US.UTF-8\n' >> /etc/environment
  sudo: true
  when: ansible_distribution == 'Ubuntu' and ansible_env.LC_ALL | default('') == ''

- include: users.yml
  tags: users

- include: ssh.yml
  tags: ssh

- name: "Install Ansible"
  pip: name=ansible
  sudo: true

- name: "Create Directories for Application"
  file: state=directory path={{item}} mode=0777 owner={{common_user}} group={{common_user}}
  with_items:
    - "{{secondfunnel_directory}}"
    - "{{secondfunnel_run_directory}}"
    - "{{secondfunnel_log_directory}}"
    - "{{secondfunnel_shared_directory}}"
  sudo: true
