---
- name: "Install zsh"
  apt: name=zsh state=latest

- name: check if oh-my-zsh is installed
  stat: path=/home/{{common_user}}/.oh-my-zsh
  register: oh_my_zsh

- name: Install oh-my-zsh
  command: git clone git://github.com/robbyrussell/oh-my-zsh.git /home/{{common_user}}/.oh-my-zsh
  when: oh_my_zsh.stat.exists == false

- name: Use templated zshrc as the default for common user
  template: src="zshrc" dest="/home/{{common_user}}/.zshrc"
