---
app_environment: "stage"
git_branch: "dev"
django_settings_module: secondfunnel.settings.test


database:
  hostname: localhost # pgbouncer -> aa1fq6h81nzaxoc.c9ahaxgbbpcf.us-west-2.rds.amazonaws.com
  port: 5432
  db_name: ebdb
  username: sf
  password: postgres


pgbouncer:
  user: postgres
  group: postgres

  config:
    database_host: aa1fq6h81nzaxoc.c9ahaxgbbpcf.us-west-2.rds.amazonaws.com
    database_port: 5432

    listen_addr: localhost
    listen_port: 5432

    user: postgres

    auth_type: md5
    auth_file: /etc/pgbouncer/userlist.txt
