---
#
# APP SETUP
#
app_environment: "stage"
git_branch: "dev"
django_settings_module: secondfunnel.settings.stage

#
# AWS SETUP
#

aws_name: "secondfunnel-{{app_environment}}"

aws_availability_zones: "us-west-2c,us-west-2b,us-west-2a"

aws_security_groups: "{{aws_name}}"

aws_ami:
  name: "{{aws_name}}-web {{ansible_date_time.date}}"
  description: "SecondFunnel {{app_environment|title}} Environment - Web Server"

aws_lb:
  name: "secondfunnel-{{app_environment}}-lb"

aws_lc:
  name: "{{aws_name}}-web-lc {{ansible_date_time.date}}"
  user_data: "{{lookup('template', 'templates/userdata.sh.j2')}}"

aws_asg:
  name: "{{aws_name}}-scaling-group"
  min_size: 1
  max_size: 1
  desired_capacity: 1
  health_check_type: "ELB"

#
# DATABASE SETUP
#

database:
  hostname: localhost # pgbouncer -> stage server (see settings below)
  port: 5432
  db_name: sfdb
  username: willet
  password: 8tJg66zMcZIRfkTu


pgbouncer:
  user: postgres
  group: postgres

  config:
    database_host: secondfunnel-stage-db.c9ahaxgbbpcf.us-west-2.rds.amazonaws.com
    database_port: 5432

    listen_addr: localhost
    listen_port: 5432

    user: postgres

    auth_type: md5
    auth_file: /etc/pgbouncer/userlist.txt
