---
app_environment: "stage"
git_branch: "dev"
django_settings_module: secondfunnel.settings.stage


database:
  hostname: localhost # pgbouncer -> stage server (see settings below)
  port: 5432
  db_name: sfdb
  username: willet
  password: 8tJg66zMcZIRfkTu


pgbouncer:
  user: postgres
  group: postgres

  config:
    database_host: secondfunnel-stage-db.c9ahaxgbbpcf.us-west-2.rds.amazonaws.com
    database_port: 5432

    listen_addr: localhost
    listen_port: 5432

    user: postgres

    auth_type: md5
    auth_file: /etc/pgbouncer/userlist.txt
