---
remote_user: vagrant
app_environment: vagrant
django_settings_module: secondfunnel.settings.dev
py_autoreload: 1


database:
  hostname: localhost # pgbouncer -> aae9bptwm2fn7s.c9ahaxgbbpcf.us-west-2.rds.amazonaws.com
  port: 6432
  db_name: sfdb
  username: sf
  password: postgres


pgbouncer:
  user: postgres
  group: postgres

  config:
    database_host: localhost
    database_port: 5432

    listen_addr: localhost
    listen_port: 6432

    user: postgres

    auth_type: md5
    auth_file: /etc/pgbouncer/userlist.txt
