{
  "tiles":{
    "wideableTemplates":{
      "image":true,
      "product":true
    },
    "imageTileWideProb":0.2
  },
  "mobileCategories":[
    {
      "subCategories":[
        {
          "tileSet":"products",
          "displayName":"Under $30",
          "name":"under-30",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%2430.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Under $50",
          "name":"under-50",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%2450.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Under $70",
          "name":"under-70",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%2470.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Under $100",
          "name":"under-100",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%24100.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Splurge!",
          "name":"splurge",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Splurge.jpg",
          "mobileHeroImage":""
        }
      ],
      "displayName":"By Price"
    },
    {
      "subCategories":[
        {
          "displayName":"For Her",
          "name":"for-her",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Gifts_for_Her.jpg",
          "mobileHeroImage":""
        },
        {
          "displayName":"For Him",
          "name":"for-him",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Gifts_for_Him.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Traveller",
          "name":"traveller",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Traveller.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Trendsetter",
          "name":"trendsetter",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Trendsetter.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Techie",
          "name":"techie",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Techie.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Outsider",
          "name":"outsider",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Outdoor.jpg",
          "mobileHeroImage":""
        }
      ],
      "displayName":"By Recipient"
    },
    {
      "subCategories":[
        {
          "displayName":"Stocking Stuffers",
          "name":"stocking-stuffers",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Stocking_Stuffers.jpg",
          "mobileHeroImage":""
        },
        {
          "displayName":"Packing Cubes",
          "name":"packing-cube",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Packing_Cubes.jpg",
          "mobileHeroImage":""
        }
      ],
      "displayName":"More Gifts"
    }
  ],
  "categoryHome":false,
  "gaAccountNumber":"UA-23764505-32",
  "column_width":341,
  "social_buttons":null,
  "stickyCategories":true,
  "generateHeroArea":false,
  "useAffiliateLinks":true,
  "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_All_Gifts.jpg",
  "home":{
    "category":"all"
  },
  "mobileHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_All_Gifts.jpg",
  "minImageWidth":400,
  "masonry":{
    "tileAspectRatio":1,
    "forceGrid":true
  },
  "categories":[
    {
      "displayName":"For Her",
      "name":"for-her",
      "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Gifts_for_Her.jpg",
      "mobileHeroImage":""
    },
    {
      "displayName":"For Him",
      "name":"for-him",
      "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Gifts_for_Him.jpg",
      "mobileHeroImage":""
    },
    {
      "subCategories":[
        {
          "tileSet":"products",
          "displayName":"Under $30",
          "name":"under-30",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%2430.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Under $50",
          "name":"under-50",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%2450.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Under $70",
          "name":"under-70",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%2470.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Under $100",
          "name":"under-100",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Under_%24100.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Splurge!",
          "name":"splurge",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Splurge.jpg",
          "mobileHeroImage":""
        }
      ],
      "displayName":"By Price"
    },
    {
      "subCategories":[
        {
          "tileSet":"products",
          "displayName":"Traveller",
          "name":"traveller",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Traveller.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Trendsetter",
          "name":"trendsetter",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Trendsetter.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Techie",
          "name":"techie",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Techie.jpg",
          "mobileHeroImage":""
        },
        {
          "tileSet":"products",
          "displayName":"Outsider",
          "name":"outsider",
          "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Outdoor.jpg",
          "mobileHeroImage":""
        }
      ],
      "displayName":"By Recipient"
    },
    {
      "displayName":"Stocking Stuffers",
      "name":"stocking-stuffers",
      "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Stocking_Stuffers.jpg",
      "mobileHeroImage":""
    },
    {
      "displayName":"Packing Cubes",
      "name":"packing-cube",
      "desktopHeroImage":"http://images.secondfunnel.com/store/ebags/holiday/Hero_Packing_Cubes.jpg",
      "mobileHeroImage":""
    }
  ]
}