---
- name: Setup newrelic apt repository
  apt_repository: repo="deb http://apt.newrelic.com/debian/ newrelic non-free" state=present
  sudo: true

- name: Add newrelic apt-key
  apt_key: url=https://download.newrelic.com/548C16BF.gpg validate_certs=no

- name: Install Server Monitor Package
  apt: name=newrelic-sysmond force=yes
  register: package_installed
  retries: 2 # sometimes the apt-key isn't quite added yet
  delay: 5

- name: Configure Server Monitor
  command: nrsysmond-config --set license_key="{{new_relic_license_key}}"
  notify: newrelic-sysmond restart
  when: package_installed|changed
