# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="avit"

# Uncomment the following line to disable bi-weekly auto-update checks.
DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
plugins=(git virtualenv)

source $ZSH/oh-my-zsh.sh

# User configuration

export PATH=$HOME/bin:/usr/local/bin:$PATH

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='mvim'
fi

export SF_DIR={{secondfunnel_directory}}
export SF_VENV_DIR={{virtualenv_directory}}

# auto activate the virtual environment if it exists
if [[ -d $SF_VENV_DIR ]]; then
  source $SF_VENV_DIR/bin/activate
fi

if [[ -d $SF_DIR/app ]]; then
  cd $SF_DIR/app
fi

if [[ -f /etc/profile.d/rds_environment.sh ]]; then
  source /etc/profile.d/rds_environment.sh
fi
