---
- name: Installs nginx web server
  yum: name=nginx state=present
  when: ansible_os_family == 'RedHat'

- name: Installs nginx web server
  apt: name=nginx state=present update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Create directories for nginx
  file: state=directory path={{item}}
  with_items:
   - /var/log/nginx

- name: Remove default nginx application config
  file: path=/etc/nginx/sites-enabled/default state=absent
  sudo: true
  sudo_user: root

#- name: Install nginx configuration
#  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
#  notify: nginx reload
#
