- name: Setup Login for pgbouncer (so we can connect to db)
  template: src=pgbouncer.userlist.txt.j2 dest=/etc/pgbouncer/userlist.txt mode=0644 owner=postgres group=postgres
  notify: pgbouncer restart
  sudo: true

- include: deploy.yml
  tags: deploy

- name: Install nginx + uwsgi config
  template: src=secondfunnel.nginx.conf dest=/etc/nginx/sites-enabled/secondfunnel.nginx.conf
  notify: nginx reload
  sudo: true
