- name: "Database Import (vagrant)"
  serial: 1
  hosts: webservers:!building
  remote_user: "{{common_user}}"
  vars:
    db_file_name: "db_production_{{ansible_env['USER']}}_{{ansible_date_time.epoch}}.dump"
  tasks:
      - name: "Import data"
        shell: "source {{virtualenv_directory}}/bin/activate && fab {{app_environment}} 'database.remote_to_local:file_name={{db_file_name}}'"
        args:
          executable: "/bin/bash"
          chdir: "{{application_directory}}/"
