- name: "Pre Configuration"
  hosts: webservers:!building
  remote_user: "{{common_user}}"
  gather_facts: False # since we are just notifying hipchat anyways
  tasks:
    - name: "Notify hipchat of configuration changes"
      local_action: hipchat
        token="{{ hipchat.token }}"
        room="{{ hipchat.room }}"
        msg="(duke) Let's rock! ({{app_environment|title}} deployment, {{play_hosts|length}} machines)"
        color="gray"
        from="Duke Nukem"
        validate_certs=no
      tags: deploy
      run_once: True
      when: (app_environment | default('vagrant') != 'vagrant') and 'autoscale' not in groups

    - name: "Notify hipchat of Auto-Scaling"
      local_action: hipchat
        token="{{ hipchat.token }}"
        room="{{ hipchat.room }}"
        msg="AutoScale - (begin) increasing web machines by 1"
        color="gray"
        from="AWS Gods"
        validate_certs=no
      tags: deploy
      run_once: True
      when: ('autoscale' in groups) and ('vagrant' not in groups)

    - name: "Disabling Auto-scaling during configuration."
      command: "aws autoscaling suspend-processes --auto-scaling-group-name '{{ aws_asg.name }}' --scaling-processes Launch Terminate HealthCheck"
      run_once: True
      when: ('autoscale' not in groups) and ('vagrant' not in groups)

- name: "Remove any (local) known hosts already for the given box"
  hosts: webservers:&vagrant
  gather_facts: no
  tasks:
    - name: "Remove KNOWN_HOSTS"
      local_action: command ssh-keygen -R '{{item}}'
      with_items:
        - "{{ansible_ssh_host}}"
        - "[{{ansible_ssh_host}}]:{{ansible_ssh_port}}"
      tags: vagrant_data_import

- name: "Bootstrap Servers"
  serial: 2
  hosts: webservers:!building
  remote_user: "{{bootstrap_user}}"
  roles:
    - { role: common, tags: common }
    - { role: aws_tools, tags: aws_tools }

- name: "Setup Database (vagrant)"
  hosts: webservers:&vagrant
  remote_user: "{{common_user}}"
  roles:
    - { role: db, tags: db }

- name: "Setup Servers"
  serial: 2
  hosts: webservers:!building
  remote_user: "{{common_user}}"
  pre_tasks:
    - name: "Gathering ec2 facts"
      ec2_facts:
      when: app_environment != "vagrant"
      tags: deploy
    - name: "De-Register Instance from LB"
      local_action: ec2_elb
      args:
        instance_id: "{{ansible_ec2_instance_id}}"
        ec2_elbs: "{{aws_lb.name}}"
        region: "{{aws_region}}"
        state: "absent"
        wait: yes
        wait_timeout: 120
      ignore_errors: yes
      when: app_environment != "vagrant"
      tags: deploy
  roles:
    - web
  post_tasks:
    - name: "Register Instance on LB"
      local_action: ec2_elb
      args:
        instance_id: "{{ansible_ec2_instance_id}}"
        ec2_elbs: "{{aws_lb.name}}"
        region: "{{aws_region}}"
        state: "present"
        wait: yes
        wait_timeout: 120
      ignore_errors: yes
      when: app_environment != "vagrant"
      tags: deploy

- name: "Post Configuration"
  hosts: webservers:!building
  remote_user: "{{common_user}}"
  gather_facts: False # since we are just notifying hipchat anyways
  tasks:
    - name: "Notify hipchat of configuration changes"
      local_action: hipchat
        token="{{ hipchat.token }}"
        room="{{ hipchat.room }}"
        msg="(goodnews)(doge) {{app_environment|title}} deployment and configuration complete. ({{play_hosts|length}} machines were updated)"
        color="green"
        from="Hubert"
        validate_certs=no
      tags: deploy
      run_once: true
      when: (app_environment | default('vagrant') != 'vagrant') and 'autoscale' not in groups

    - name: "Notify hipchat of Auto-Scaling"
      local_action: hipchat
        token="{{ hipchat.token }}"
        room="{{ hipchat.room }}"
        msg="AutoScale - (end) increased web machines by 1"
        color="green"
        from="AWS Gods"
        validate_certs=no
      tags: deploy
      run_once: True
      when: ('autoscale' in groups) and ('vagrant' not in groups)

    - name: "Re-Enable Auto-scaling for after configuration."
      command: "aws autoscaling resume-processes --auto-scaling-group-name '{{ aws_asg.name }}' --scaling-processes Launch Terminate HealthCheck"
      run_once: True
      when: ('autoscale' not in groups) and ('vagrant' not in groups)
