{
  "tiles":{
    "imageTileWideProbability":0.2,
    "wideableTemplates":{
      "image":true,
      "product": true
    }
  },
  "home":{
    "category":"mothersday"
  },
  "social_buttons":null,
  "desktopHeroImage":"",
  "ga_account_number":"UA-23764505-25",
  "mobileHeroImage":"",
  "column_width":341,
  "categoryHome":false,
  "masonry":{
    "tileAspectRatio":1,
    "forceGrid":true
  },
  "minImageWidth":675,
  "stickyCategories":false,
  "categories":[
    {
      "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/allmothersdaygifts_jfrjua.png",
      "subCategories":[
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaytop25giftsmom_bftc2k.png",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaytop25giftsmom_bftc2k.png",
          "displayName":"Top 25",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/Top25GiftsMom_steamgrill_bnsodg.jpg",
          "name":"top-25"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaygiftsunder50_csj7xu.png",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaygiftsunder50_csj7xu.png",
          "displayName":"Under $50",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/GiftsUnder50_apron_glbpne.jpg",
          "name":"under-50"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaygiftsunder100_xib5zg.png",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaygiftsunder100_xib5zg.png",
          "displayName":"Under $100",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/GiftsUnder100_skillet_hcqjpw.jpg",
          "name":"under-100"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/GourmetGiftsforMom_cnevtl.jpg",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/GourmetGiftsforMom_cnevtl.jpg",
          "displayName":"Gourmet",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/GiftsForMom_kitchenaid_fjhmiz.jpg",
          "name":"gourmet"
        }
      ],
      "displayName":"Gifts for Mom",
      "name":"mothersday",
      "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/allmothersdaygifts_jfrjua.png"
    },
    {
      "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaybakingrecipes_sgpwf3.png",
      "subCategories":[
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaybakingrecipes_sgpwf3.png",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaybakingrecipes_sgpwf3.png",
          "displayName":"Baking",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/BakingRecipes_lavender_macarons_ogxrk9.jpg",
          "name":"baking"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaybrunchrecipes_ccmvso.png",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaybrunchrecipes_ccmvso.png",
          "displayName":"Brunch",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/BrunchRecipes_eggs_benedict_fat4qs.jpg",
          "name":"brunch"
        }
      ],
      "displayName":"Mother\u2019s Day Recipes",
      "name":"recipes",
      "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426905789/mothersdaybakingrecipes_sgpwf3.png"
    }
  ]
}