{
  "tiles":{
    "imageTileWideProbability":0.2,
    "widable_templates":{
      "image":true,
      "product": true
    }
  }
  "social_buttons":null,
  "desktop_hero_image":"",
  "ga_account_number":"UA-23764505-25",
  "mobile_hero_image":"",
  "column_width":341,
  "categoryHome":false,
  "masonry":{
    "tileAspectRatio":1,
    "forceGrid":true
  },
  "minImageWidth":675,
  "stickyCategories":false,
  "categories":[
    {
      "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/AllMothersDayGifts_xurrha.jpg",
      "subCategories":[
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayTop25GiftsMom_feeud5.jpg",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayTop25GiftsMom_feeud5.jpg",
          "displayName":"Top 25",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/Top25GiftsMom_steamgrill_bnsodg.jpg",
          "name":"top-25"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayGiftsUnder50_b61cxz.jpg",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayGiftsUnder50_b61cxz.jpg",
          "displayName":"Under $50",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/GiftsUnder50_apron_glbpne.jpg",
          "name":"under-50"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayGiftsUnder100_dni50c.jpg",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayGiftsUnder100_dni50c.jpg",
          "displayName":"Under $100",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/GiftsUnder100_skillet_hcqjpw.jpg",
          "name":"under-100"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/GourmetGiftsforMom_cnevtl.jpg",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/GourmetGiftsforMom_cnevtl.jpg",
          "displayName":"Gourmet",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/GiftsForMom_kitchenaid_fjhmiz.jpg",
          "name":"gourmet"
        }
      ],
      "displayName":"Gifts for Mom",
      "name":"all",
      "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/AllMothersDayGifts_xurrha.jpg"
    },
    {
      "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/BakingRecipes_lavender_macarons_ogxrk9.jpg",
      "subCategories":[
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayBakingRecipes_pmgyay.jpg",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayBakingRecipes_pmgyay.jpg",
          "displayName":"Baking",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/BakingRecipes_lavender_macarons_ogxrk9.jpg",
          "name":"baking"
        },
        {
          "mobileHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayBrunchRecipes_o2xhn6.jpg",
          "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892662/MothersDayBrunchRecipes_o2xhn6.jpg",
          "displayName":"Brunch",
          "thumbnail":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/BrunchRecipes_eggs_benedict_fat4qs.jpg",
          "name":"brunch"
        }
      ],
      "displayName":"Mother\u2019s Day Recipes",
      "name":"recipes",
      "desktopHeroImage":"http://res.cloudinary.com/secondfunnel/image/upload/v1426892663/BakingRecipes_lavender_macarons_ogxrk9.jpg"
    }
  ]
}